update background services

diff --git a/tests/roles/mariadb_copy/tasks/main.yaml b/tests/roles/mariadb_copy/tasks/main.yaml
--- a/tests/roles/mariadb_copy/tasks/main.yaml
+++ b/tests/roles/mariadb_copy/tasks/main.yaml
@@ -75,48 +75,48 @@
   retries: 25
   delay: 2
 
-- name: check that the Galera database cluster members are online and synced
-  no_log: "{{ use_no_log }}"
-  ansible.builtin.shell: |
-    {{ shell_header }}
-    {{ oc_header }}
-    {{ mariadb_copy_shell_vars_src }}
-    for i in "${!SOURCE_GALERA_MEMBERS[@]}"; do
-      echo "Checking for the database node $i WSREP status Synced"
-      oc rsh mariadb-copy-data mysql \
-        -h "${SOURCE_GALERA_MEMBERS[$i]}" -uroot -p"$SOURCE_DB_ROOT_PASSWORD" \
-        -e "show global status like 'wsrep_local_state_comment'" | \
-        grep -qE "\bSynced\b"
-    done
+# - name: check that the Galera database cluster members are online and synced
+#   no_log: "{{ use_no_log }}"
+#   ansible.builtin.shell: |
+#     {{ shell_header }}
+#     {{ oc_header }}
+#     {{ mariadb_copy_shell_vars_src }}
+#     for i in "${!SOURCE_GALERA_MEMBERS[@]}"; do
+#       echo "Checking for the database node $i WSREP status Synced"
+#       oc rsh mariadb-copy-data mysql \
+#         -h "${SOURCE_GALERA_MEMBERS[$i]}" -uroot -p"$SOURCE_DB_ROOT_PASSWORD" \
+#         -e "show global status like 'wsrep_local_state_comment'" | \
+#         grep -qE "\bSynced\b"
+#     done
 
-- name: Get the count of not-OK source databases
-  no_log: "{{ use_no_log }}"
-  ansible.builtin.shell: |
-    {% if pulled_openstack_configuration_shell_headers is defined %}
-    {{ pulled_openstack_configuration_shell_headers }}
-    {% else %}
-    . ~/.source_cloud_exported_variables
-    {% endif %}
+# - name: Get the count of not-OK source databases
+#   no_log: "{{ use_no_log }}"
+#   ansible.builtin.shell: |
+#     {% if pulled_openstack_configuration_shell_headers is defined %}
+#     {{ pulled_openstack_configuration_shell_headers }}
+#     {% else %}
+#     . ~/.source_cloud_exported_variables
+#     {% endif %}
 
-    test -z "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK"  || [ "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK" = " " ] && echo "OK" || echo "CHECK FAILED"
-  register: result
-  failed_when: result.rc != 0 or 'CHECK FAILED' in result.stdout
+#     test -z "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK"  || [ "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK" = " " ] && echo "OK" || echo "CHECK FAILED"
+#   register: result
+#   failed_when: result.rc != 0 or 'CHECK FAILED' in result.stdout
 
-- name: test connection to podified DBs (show databases)
-  no_log: "{{ use_no_log }}"
-  ansible.builtin.shell:
-    cmd: "{{ lookup('ansible.builtin.template', 'pre_checks.bash') }}"
+# - name: test connection to podified DBs (show databases)
+#   no_log: "{{ use_no_log }}"
+#   ansible.builtin.shell:
+#     cmd: "{{ lookup('ansible.builtin.template', 'pre_checks.bash') }}"
 
-- name: dump databases
-  no_log: "{{ use_no_log }}"
-  ansible.builtin.shell:
-    cmd: "{{ lookup('ansible.builtin.template', 'dump_dbs.bash') }}"
+# - name: dump databases
+#   no_log: "{{ use_no_log }}"
+#   ansible.builtin.shell:
+#     cmd: "{{ lookup('ansible.builtin.template', 'dump_dbs.bash') }}"
 
-- name: restore databases
-  no_log: "{{ use_no_log }}"
-  ansible.builtin.shell:
-    cmd: "{{ lookup('ansible.builtin.template', 'restore_dbs.bash') }}"
+# - name: restore databases
+#   no_log: "{{ use_no_log }}"
+#   ansible.builtin.shell:
+#     cmd: "{{ lookup('ansible.builtin.template', 'restore_dbs.bash') }}"
 
-- name: Verify MariaDB data imported
-  ansible.builtin.include_tasks:
-    file: mariadb_verify.yaml
+# - name: Verify MariaDB data imported
+#   ansible.builtin.include_tasks:
+#     file: mariadb_verify.yaml
