Exit early if DataPlaneDeployment is failing

diff --git a/tests/roles/dataplane_adoption/tasks/main.yaml b/tests/roles/dataplane_adoption/tasks/main.yaml
--- a/tests/roles/dataplane_adoption/tasks/main.yaml
+++ b/tests/roles/dataplane_adoption/tasks/main.yaml
@@ -291,20 +291,33 @@
   ansible.builtin.shell: |
     {{ shell_header }}
     {{ oc_header }}
-    NODESET_NAME=openstack
+
     DEPLOYMENT_NAME=openstack
-    echo "========= AEE Pods ========="
-    oc get pod -l osdpd=${DEPLOYMENT_NAME}
-    LAST_SERVICE_NAME=$(oc get osdpns ${NODESET_NAME} -o jsonpath='{.spec.services}' | jq -r last)
-    echo "========= Last service name: ${LAST_SERVICE_NAME} ========="
-    LAST_SERVICE_POD=$(oc get pod -l job-name=${LAST_SERVICE_NAME}-${DEPLOYMENT_NAME} -o name)
-    echo "========= Last service POD name: ${LAST_SERVICE_POD} ========="
-    oc get ${LAST_SERVICE_POD} -o jsonpath='{.status.phase}{"\n"}' | grep Succeeded
-    oc get osdpd openstack -o jsonpath='{.status.deployed}{"\n"}' | grep true
+    TRIES=180
+    DELAY=10
+    ALLOWED_JOB_RETRIES=3
+
+    for i in $(seq $TRIES)
+    do
+        ready=$(oc get osdpd/$DEPLOYMENT_NAME -o jsonpath='{.status.conditions[0].status}')
+        if [ "$ready" == "True" ]; then
+            echo "Deployment is Ready"
+            exit 0
+        else
+            failed=$(oc get jobs -l osdpd=$DEPLOYMENT_NAME -o jsonpath="{.items[?(@.status.failed > $ALLOWED_JOB_RETRIES)].metadata.name}")
+            if [ ! -z "${failed}" ]; then
+                echo "There are failed AnsibleEE jobs: $failed"
+                exit 1
+            fi
+        fi
+
+    sleep $DELAY
+    done
+
+    echo "Run out of retries"
+    exit 2
+
   register: osdpd_running_result
-  until: osdpd_running_result is success
-  retries: 25
-  delay: 60
 
 - name: Complete Nova services Wallaby->Antelope FFU
   ansible.builtin.include_tasks:
diff --git a/tests/roles/dataplane_rhev_adoption/tasks/main.yaml b/tests/roles/dataplane_rhev_adoption/tasks/main.yaml
--- a/tests/roles/dataplane_rhev_adoption/tasks/main.yaml
+++ b/tests/roles/dataplane_rhev_adoption/tasks/main.yaml
@@ -299,6 +299,31 @@
   ansible.builtin.shell: |
     {{ shell_header }}
     {{ oc_header }}
-    oc wait --for condition=Ready osdpns/openstack --timeout=40m
+
+    DEPLOYMENT_NAME=openstack
+    TRIES=240
+    DELAY=10
+    ALLOWED_JOB_RETRIES=3
+
+    for i in $(seq $TRIES)
+    do
+        ready=$(oc get osdpd/$DEPLOYMENT_NAME -o jsonpath='{.status.conditions[0].status}')
+        if [ "$ready" == "True" ]; then
+            echo "Deployment is Ready"
+            exit 0
+        else
+            failed=$(oc get jobs -l osdpd=$DEPLOYMENT_NAME -o jsonpath="{.items[?(@.status.failed > $ALLOWED_JOB_RETRIES)].metadata.name}")
+            if [ ! -z "${failed}" ]; then
+                echo "There are failed AnsibleEE jobs: $failed"
+                exit 1
+            fi
+        fi
+
+    sleep $DELAY
+    done
+
+    echo "Run out of retries"
+    exit 2
+
   # TODO: work on network configuration for making possible to run this task on other IP ranges
   when: "edpm_node_ip.startswith('192.168.23')"
